- name: Install Jenkins/Docker
  hosts: localhost
  tasks:
    - name: Import jenkins key from url
      ansible.builtin.rpm_key:
        state: present
        key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

    - name: Download Long Term Jenkins release
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Install packages
      yum:
        name:
        - java
        - jenkins
        - docker
        state: latest

    - name: Give Jenkins permission
      command: usermod -a -G docker jenkins

    - name: Start jenkins
      ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Start docker
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Get initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: initial_admin_password

    - name: Print initial admin password
      debug:
        msg: "{{initial_admin_password.stdout}}"
